name: Super-Linter #workflow name

on: push #event

jobs: #actions to happen
  super-lint: #action name
    name: Lint code base
    runs-on: ubuntu-latest
    steps: # individual processes in the action
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
